# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=140)),
                ('last_name', models.CharField(max_length=140)),
                ('born', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=50)),
                ('property_type', models.IntegerField(choices=[(0, 'Housing'), (1, 'Commercial property')], default=0)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacant', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='rent.Owner')),
            ],
            options={
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_first_name', models.CharField(max_length=140)),
                ('tenant_last_name', models.CharField(max_length=140)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('property_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='rent.Property')),
            ],
            options={
                'ordering': ('end_date',),
            },
        ),
    ]
