# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-28 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('contract_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='rent.RentalContract')),
            ],
        ),
    ]
