# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-28 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20180728_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
